liquibase/docker

Dockerfile, README.md
1. Created more jar downloads (curl) in Docker.
2. Changed folder structure to make things simpler and more user-friendly.
3. Upgraded image to openjdk:13
4. Improved and matched the README DOC page with the new changes.
5. Improved and matched commands in the Dockerfile file with the new changes.
6.  All use cases from the updated README.md were tested locally and successfully after running the "docker build liquibase/liquibase" command.
=> Docker improvements <2020-05-03>

3.10.x/Dockerfile, 3.10.x/docker-entrypoint.sh, Dockerfile, docker-entrypoint.sh
https://github.com/docker-library/official-images/pull/8409
=> Added docker-entrypoint.sh based on feedback

3.10.x/Dockerfile, Dockerfile
I was facing issues with MSSQL Server 15.0.4033.1 so I had to update the driver.
=> Update MSSQL driver to 8.4.1.jre11

Dockerfile
=> Adding Oracle JDBC Driver

liquibase.docker.properties
This will avoid the prompt:
Do you want to see this operation's report in Liquibase Hub, which improves team collaboration?
If so, enter your email. If not, enter [N] to no longer be prompted, or [S] to skip for now, but ask again next time (default "S"):
(...) Which is not good for automated scripts.
=> Add liquibase.headless true

Dockerfile
=> Bump to Liquibase 4.3.5

docker-entrypoint.sh
New defaults file option support
=> Change to accept --defaults-file argument for new 4.4.0 CLI

.github/reviewer-lottery.yml, .github/workflows/release-automation.yml
add docker build automation workflow for core and snowflake
=> DAT-4564 docker build automation workflow for core and snowflake

Dockerfile
Make sure the OS is fully up to date as part of docker builds
=> Added apt-get upgrade to docker build

.github/dependabot.yml
Add dependabot docker configuration
=> add docker to dependabot config

Dockerfile
=> Bump lpm to v0.1.7

Dockerfile
Updating the base image to ubuntu jammy should resolve #178 and #176
=> update base to Ubuntu Jammy 22.04

.github/workflows/create-release.yml
- Support for both amd64 and arm64 platforms
closes #126
=> feat: build and push liquibase docker images via GH

Dockerfile
* Upgrade LPM version to 0.22 (this one has arm64 support)
* add logic to download correct LPM architecture
Some help: https://blog.thesparktree.com/docker-multi-arch-github-actions
=> Fix lpm usage on arm image

.github/workflows/create-release.yml
these changes broke the release process because a matrix strategy is only visible per-job.  Will need to refactor these changes.
=> revert changes to release workflow

.github/workflows/create-release.yml, README.md, examples/aws/Dockerfile.awscli, examples/aws/Dockerfile.slim.awscli, examples/mssql/Dockerfile.slim.sqlcmd, examples/mssql/Dockerfile.sqlcmd, examples/oracle/Dockerfile.slim.sqlplus, examples/postgres/Dockerfile.psql, examples/postgres/Dockerfile.slim.psql
chore(create-release.yml): update create-release.yml to support alpin…e image and add suffix to image name
docs(README.md): add documentation for liquibase alpine image, including functionality, usage, and examples
=> DAT-14865  Add the overview for liquibase-alpine

docker-entrypoint.sh
fix: `docker-entrypoint.sh` : explicitly adding liquibase initialization command for H2
=> DAT-16879: explicitly adding liquibase initialization command for H2

README.md
feat: `README.md`: adding a pixel for scarf.sh for analytics and tracking
=> 🔧 DAT-17888: adding a pixel for scraf.sh

Dockerfile, Dockerfile.alpine
fixes security vulnerability in golang
=> upgrade lpm to 0.2.5

.github/workflows/create-release.yml
✨ (create-release.yml): Add support for dry run mode in the release workflow to prevent unintended changes from being pushed to the repository.
=> DAT-18302   DevOps :: Add Dry Run capabilities to liquibase packages

.github/workflows/create-release.yml
fix: `.github/workflows/create-release.yml`: handle dryRun value here as a safe side.
=> 🔧 DAT-18995: handle dryRun value here as a safe side.

.github/workflows/create-release.yml
=> Revert "🔧 DAT-18995: handle dryRun value here as a safe side."

.github/workflows/create-release.yml
=> Revert "🛠️ TEST DAT-18995: comment code to test if PR gets created on a dryRun "

DockerfilePro
This pull request refactors the architecture-specific logic in the `DockerfilePro` to improve readability and maintainability. The most important changes include restructuring the conditional logic for determining architecture, updating the handling of temporary files, and ensuring directories are created with the `-p` flag.
* Refactored the conditional logic for determining the architecture (`amd64` or `arm64`) by replacing the `case` statement with an `if-elif-else` structure, making the code more readable and consistent.
* Introduced a new variable `DOWNLOAD_SHA256` to handle the SHA256 checksum for the downloaded file, improving clarity and reducing potential errors.
1. Avoids shell variable scoping issues by using if/elif instead of case.
2. Uses full paths (/tmp/, /liquibase/bin/) …
=> 🔧 Fix LPM installation in DockerfilePro for architecture detection 
